# Databricks notebook source
# MAGIC %sql
# MAGIC 
# MAGIC SELECT "Hello WORLD"
# MAGIC SELECT "2 Hello"
# MAGIC SELECT "3 Hello"
# MAGIC SELECT "4 HELLO"
# MAGIC SELECT "HELLO 5"
# MAGIC SELECT "HELLO 8"
# MAGIC SeLEct "hELLO 9"
# MAGIC SELECT "hello 10"
